Puppet 6 testing complete

diff --git a/puppet_install b/puppet_install
--- a/puppet_install
+++ b/puppet_install
@@ -14,8 +14,9 @@ done
 # Global settings
 PUPPET=/opt/puppetlabs/bin/puppet
 PUPPETSERVER=/opt/puppetlabs/bin/puppetserver
-PUPPET_REPO_URL=https://yum.puppet.com/puppet6/puppet6-release-el-7.noarch.rpm
 HOSTNAME=$(hostname)
+OS_NAME=el
+OS_VER=7
 REQUIRED_PKGS_COMMON=( bind-utils lsof )
 REQUIRED_PKGS_MASTER=( PyYAML )
 REQUIRED_PKGS_AGENT=()
@@ -23,12 +24,14 @@ REQUIRED_PKGS_AGENT=()
 # Command line option defaults
 VERBOSE=0
 DEBUG=0
+FORCE="${PUPINSTALLFORCE:-0}"
 BKUP_DIR="${PUPBKUPDIR:-/backups}"
 BUILD_TYPE="$PUPBUILDTYPE"           #master | agent (allow to be set by env var)
 CONFIG_TYPE="$PUPCONFIGTYPE"         #new | restore | r10k (allow env var)
 AGENT_CERTNAME="$PUPCERTNAME"        #allow override hostname
 AGENT_PUPMASTER="$PUPMASTER"         #ip or valid DNS hostname of pupmaster
 DNS_ALT_NAMES="$PUPCAALTNAMES"       #dns alt names for puppet certificate
+PUP_VERSION="$PUPINSTALLVER"      #version of puppet to install (5 or 6)
 
 
 ###
@@ -44,10 +47,12 @@ while :; do
             echo "    -b <backup_dir>       (path to backup directory, containing *_puppet_config.tar.gz files)"
             echo "    -d                    (enable debug mode)"
             echo "    -D <dns_alt_names>    (Comma separated list of alternate names for puppet CA certificate)"
+            echo "    -F                    (Force install. Install over the top of existing setup)"
             echo "    -m                    (build a master)"
             echo "    -M <new|restore|r10k> (how to configure puppet master)"
             echo "    -P <Puppet Master IP> (IP or hostname of puppet master, used only for agent build type)"
             echo "    -v                    (enable verbose mode)"
+            echo "    -V <puppet version>   Version of puppet to install (ie: 5 or 6)"
             exit
             ;;
         -a) BUILD_TYPE=agent
@@ -64,6 +69,8 @@ while :; do
         -D) DNS_ALT_NAMES="$2"
             shift
             ;;
+        -F) FORCE=1
+            ;;
         -m) BUILD_TYPE=master
             ;;
         -M) CONFIG_TYPE="$2"
@@ -73,6 +80,9 @@ while :; do
             shift
             ;;
         -v) VERBOSE=1
+            ;;
+        -V) PUP_VERSION="$2"
+            shift
             ;;
         --) shift
             break
@@ -86,28 +96,45 @@ while :; do
     shift
 done
 
-# assert valid build_type
-case "$BUILD_TYPE" in
-    master)
-        # check config_type ... only relevant if build_type is MASTER
-        if [[ " new restore r10k " =~ " $CONFIG_TYPE " ]]; then
-            : #pass
-        else
-            die "Missing or invalid config type: '$CONFIG_TYPE' for puppet master"
-        fi
-        ;;
-    agent)
-        [[ -n "$AGENT_PUPMASTER" ]] || die 'Missing Pup Master IP or hostname'
-        ;;
-    *)
-        die "Invalid build type '$BUILD_TYPE'"
-        ;;
-esac
 
 
 ###
 # Functions
 ###
+
+assert_valid_build_type() {
+    case "$BUILD_TYPE" in
+        master)
+            # check config_type ... only relevant if build_type is MASTER
+            if [[ " new restore r10k " =~ " $CONFIG_TYPE " ]]; then
+                : #pass
+            else
+                die "Missing or invalid config type: '$CONFIG_TYPE' for puppet master"
+            fi
+            ;;
+        agent)
+            [[ -n "$AGENT_PUPMASTER" ]] || die 'Missing Pup Master IP or hostname'
+            ;;
+        *)
+            die "Invalid build type '$BUILD_TYPE'"
+            ;;
+    esac
+}
+
+
+clean_old() {
+    log "enter..."
+    [[ "$DEBUG" -gt 0 ]] && set -x
+    [[ "$FORCE" -lt 1 ]] && return 0  # Do nothing if force is not set
+    # remove puppet rpm packages
+    yum list installed | awk '/puppet/ {print $1}' \
+    | xargs -r yum -y remove
+    # delete puppet install locations
+    find /etc/puppetlabs -delete
+    find /opt/puppetlabs -delete
+    find /var/cache/r10k -delete
+    find /etc/yum.repos.d/ -type f -name 'puppet*' -delete
+}
 
 
 install_required_pkgs() {
@@ -130,8 +157,11 @@ install_required_pkgs() {
 install_puppet() {
     log "enter..."
     [[ "$DEBUG" -gt 0 ]] && set -x
+    YUM_REPO_URL=https://yum.puppet.com/puppet${PUP_VERSION}/puppet${PUP_VERSION}-release-${OS_NAME}-${OS_VER}.noarch.rpm
     ls /etc/yum.repos.d/puppet*.repo &>/dev/null \
-    || yum -y install $PUPPET_REPO_URL
+    || yum -y install $YUM_REPO_URL
+    ls /etc/yum.repos.d/puppet*.repo &>/dev/null \
+    || die "Failed to install Yum repo file"
 
     local pkglist
     case "$BUILD_TYPE" in
@@ -200,25 +230,53 @@ ENDHERE
 
 
 configure_ca() {
-    # CA setup, see: https://puppet.com/docs/puppet/6.0/ssl_regenerate_certificates.html
+    # For puppet6, see: https://puppet.com/docs/puppet/6.0/ssl_regenerate_certificates.html
     log "enter..."
     [[ "$DEBUG" -gt 0 ]] && set -x
+    local hn_short=$( hostname )
+    local hn_long=$( hostname -f )
+
+    # Stop if already setup
+    ##puppet6
     [[ -f /etc/puppetlabs/puppet/ssl/certs/ca.pem ]] && {
+#    ##puppet4
+#    [[ -d /etc/puppetlabs/puppet/ssl/ca ]] && {
         log 'CA already configured, skipping.'
         return 0
     }
 
+    # Setup Alt Names
+    ##puppet6
     local ip_alts=( $( for i in $(hostname -I); do echo "IP:$i"; done ) )
-    local alt_names=$( echo "${ip_alts[@]} $DNS_ALT_NAMES" \
+#    ##puppet4
+#    local ip_alts=( $(hostname -I) )
+#
+    local alt_names=$( echo "${ip_alts[@]} DNS:$hn_short $DNS_ALT_NAMES" \
         | sed -e 's/^[ \t]*//;s/[ \t]*$//' \
         | sed -e 's/ /,/g'
         )
-    $PUPPETSERVER ca setup --subject-alt-names $alt_names
-    $PUPPETSERVER start
-    sleep 5
-    $PUPPETSERVER ca list -a
-    $PUPPETSERVER stop
-    sleep 5
+
+    # Create CA cert
+    ##puppet6
+    $PUPPETSERVER ca setup \
+        --subject-alt-names $alt_names \
+        --ca-name $hn_long \
+        --certname $hn_long
+    #$PUPPETSERVER start
+    #sleep 5
+    #$PUPPETSERVER ca list -a
+    #$PUPPETSERVER stop
+    #sleep 5
+#    ##puppet4
+#    $PUPPET cert list -a
+#    $PUPPET config set certname $HOSTNAME --section master
+#    $PUPPET certificate generate \
+#        --dns-alt-names $alt_names \
+#        --ca-location local \
+#        $HOSTNAME
+#    #$PUPPET cert sign $HOSTNAME --allow-dns-alt-names
+#    # don't know what this does, but puppetserver won't start otherwise
+#    $PUPPET certificate find $HOSTNAME --ca-location local &>/dev/null
 }
 
 
@@ -287,6 +345,8 @@ agent_run() {
 
 # Always perform these steps
 assert_root
+assert_valid_build_type
+clean_old
 install_required_pkgs
 install_puppet
 
@@ -301,12 +361,8 @@ case "$BUILD_TYPE" in
                 restore_ca
                 ;;
             new)
-                #configure_ca
-                create_autosign
-                ;;
-            r10k)
-                restore_ca
-                create_autosign
+                configure_ca
+#                create_autosign
                 ;;
         esac
         #puppetserver start
